# version of docker
version: '3.8'
services: 
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"
    volumes: 
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis 
    environment: 
      - DATABASE_URL=postgres://postgres:password@db:5432/cool-app
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/myapp
    command:
      - |
        rails db:migrate
        rails db:seed
        rails s -p 3000 -b '0.0.0.0'

volumes: 
  dbdata:
 