 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wizards", type: :request do
  # Wizard. As you add validations to Wizard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Wizard.create! valid_attributes
      get wizards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wizard = Wizard.create! valid_attributes
      get wizard_url(wizard)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wizard_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      wizard = Wizard.create! valid_attributes
      get edit_wizard_url(wizard)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Wizard" do
        expect {
          post wizards_url, params: { wizard: valid_attributes }
        }.to change(Wizard, :count).by(1)
      end

      it "redirects to the created wizard" do
        post wizards_url, params: { wizard: valid_attributes }
        expect(response).to redirect_to(wizard_url(Wizard.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Wizard" do
        expect {
          post wizards_url, params: { wizard: invalid_attributes }
        }.to change(Wizard, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wizards_url, params: { wizard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wizard" do
        wizard = Wizard.create! valid_attributes
        patch wizard_url(wizard), params: { wizard: new_attributes }
        wizard.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wizard" do
        wizard = Wizard.create! valid_attributes
        patch wizard_url(wizard), params: { wizard: new_attributes }
        wizard.reload
        expect(response).to redirect_to(wizard_url(wizard))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wizard = Wizard.create! valid_attributes
        patch wizard_url(wizard), params: { wizard: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wizard" do
      wizard = Wizard.create! valid_attributes
      expect {
        delete wizard_url(wizard)
      }.to change(Wizard, :count).by(-1)
    end

    it "redirects to the wizards list" do
      wizard = Wizard.create! valid_attributes
      delete wizard_url(wizard)
      expect(response).to redirect_to(wizards_url)
    end
  end
end
